import type { Lang } from "./i18n";

// UI-chrome dictionary. Content (articles/courses/...) lives in the DB
// with separate Fa/En fields instead of auto-translation.

const fa = {
  brandTagline: "هوش مصنوعی کاربردی برای کار، مهندسی و زندگی",
  nav: {
    home: "خانه",
    learn: "آموزش AI",
    courses: "دوره‌ها",
    tools: "ابزارهای AI",
    projects: "پروژه‌ها",
    blog: "بلاگ",
    journey: "مسیر من",
    about: "درباره",
    work: "همکاری با من",
    contact: "تماس",
    dashboard: "داشبورد",
    admin: "مدیریت",
    login: "ورود / ثبت‌نام",
    logout: "خروج",
    search: "جستجو...",
  },
  hero: {
    badge: "آموزش عملی هوش مصنوعی",
    titleA: "هوش مصنوعی را در دنیای واقعی",
    titleB: "یاد بگیر و به کار بگیر",
    sub: "من محمد پرایی هستم؛ مهندس برق و practitioner هوش مصنوعی. اینجا خبری از تئوری خشک و اخبار زرد نیست — یاد می‌گیری چطور از AI در مهندسی، کسب‌وکار و زندگی روزمره واقعاً استفاده کنی.",
    ctaStart: "شروع یادگیری",
    ctaExplore: "مشاهده آموزش‌ها",
    ctaWork: "همکاری با من",
    philosophy: "یاد بگیر. تست کن. بساز. به اشتراک بگذار.",
  },
  home: {
    statsLearners: "یادگیرنده",
    statsTutorials: "آموزش و مقاله",
    statsCourses: "دوره آموزشی",
    statsTools: "ابزار بررسی‌شده",
    learnTitle: "مرکز یادگیری AI",
    learnSub: "از صفر تا کاربرد حرفه‌ای؛ مسیر یادگیری‌ات را انتخاب کن.",
    featuredCourses: "دوره‌های منتخب",
    featuredCoursesSub: "آموزش‌های ساخت‌یافته، پروژه‌محور و کاربردی.",
    latestArticles: "تازه‌ترین مقالات",
    latestArticlesSub: "یادداشت‌های عملی از تجربه کار با AI.",
    toolsTitle: "ابزارهایی که خودم تست کرده‌ام",
    toolsSub: "بدون تبلیغ؛ فقط ابزارهایی که واقعاً ارزش وقت تو را دارند.",
    projectsTitle: "پروژه‌ها و کیس‌استادی‌ها",
    projectsSub: "مسئله واقعی، راه‌حل واقعی، نتیجه واقعی.",
    journeyTitle: "در مسیر ساختن",
    journeySub: "دارم علنی می‌سازم و یاد می‌گیرم؛ همراه شو.",
    igTitle: "اینستاگرام من",
    igSub: "آموزش‌های کوتاه و روزمره AI را آنجا دنبال کن.",
    igFollow: "فالو در اینستاگرام",
    newsletterTitle: "درس‌های عملی AI در اینباکس تو",
    newsletterSub: "هفته‌ای یک ایمیل کوتاه و کاربردی. بدون اسپم.",
    newsletterPlaceholder: "ایمیل شما",
    newsletterButton: "عضویت",
    newsletterDone: "عضویتت ثبت شد. به‌زودی می‌بینمت!",
    viewAll: "مشاهده همه",
    free: "رایگان",
    paid: "پولی",
    comingSoon: "به‌زودی",
    min: "دقیقه",
    lessons: "درس",
  },
  footer: {
    about: "محمد پرایی — مهندس برق و مدرس هوش مصنوعی کاربردی. کمک می‌کنم از AI در کار، مهندسی و زندگی واقعاً استفاده کنی.",
    quickLinks: "دسترسی سریع",
    categories: "دسته‌بندی‌های محبوب",
    connect: "ارتباط",
    rights: "کلیه حقوق محفوظ است.",
    privacy: "حریم خصوصی",
    terms: "قوانین استفاده",
    madeWith: "ساخته‌شده با دقت برای یادگیرندگان AI",
  },
  auth: {
    loginTitle: "ورود / ثبت‌نام",
    loginSub: "با شماره موبایل وارد شو؛ بدون رمز عبور.",
    phoneLabel: "شماره موبایل",
    phonePlaceholder: "09123456789",
    sendCode: "ارسال کد تایید",
    codeLabel: "کد تایید ۶ رقمی",
    verify: "تایید و ورود",
    resend: "ارسال مجدد کد",
    backToPhone: "تغییر شماره",
    demoBox: "حالت نمایشی فعال است — کد تایید:",
    demoHint: "در نسخه نهایی این کد با پیامک ارسال می‌شود.",
    errors: {
      invalid_phone: "شماره موبایل معتبر نیست.",
      cooldown: "کمی صبر کن و دوباره تلاش کن.",
      rate_limited: "تعداد درخواست زیاد است؛ بعداً تلاش کن.",
      sms_failed: "ارسال پیامک ناموفق بود.",
      wrong_code: "کد واردشده اشتباه است.",
      expired: "کد منقضی شده؛ کد جدید بگیر.",
      locked: "به‌خاطر تلاش زیاد قفل شد؛ کد جدید بگیر.",
      not_found: "کدی برای این شماره پیدا نشد.",
    } as Record<string, string>,
  },
  dashboard: {
    title: "داشبورد من",
    welcome: "خوش برگشتی",
    overview: "نمای کلی",
    myCourses: "دوره‌های من",
    saved: "ذخیره‌شده‌ها",
    history: "تاریخچه یادگیری",
    settings: "تنظیمات حساب",
    profile: "پروفایل",
    enrolled: "دوره ثبت‌نام‌شده",
    completed: "دوره تکمیل‌شده",
    inProgress: "در حال یادگیری",
    continueCourse: "ادامه یادگیری",
    noCourses: "هنوز در دوره‌ای ثبت‌نام نکرده‌ای.",
    browseCourses: "مشاهده دوره‌ها",
    noSaved: "هنوز چیزی ذخیره نکرده‌ای.",
    noHistory: "تاریخچه‌ای ثبت نشده است.",
    name: "نام و نام خانوادگی",
    phone: "شماره موبایل",
    email: "ایمیل (اختیاری)",
    language: "زبان ترجیحی",
    save: "ذخیره تغییرات",
    saved2: "تغییرات ذخیره شد.",
    notifications: "اعلان‌ها",
    noNotifications: "اعلانی نداری.",
    devices: "دستگاه‌ها",
    logoutAll: "خروج از همه دستگاه‌ها",
    progress: "پیشرفت",
  },
  courses: {
    enroll: "ثبت‌نام در دوره",
    enrolled: "ثبت‌نام شده‌ای",
    loginToEnroll: "برای ثبت‌نام وارد شو",
    notifyMe: "خبرم کن",
    outcomes: "چه چیزهایی یاد می‌گیری",
    audience: "این دوره برای کیست",
    prereq: "پیش‌نیازها",
    modules: "سرفصل‌ها",
    instructor: "مدرس",
    level: "سطح",
    freeLesson: "رایگان",
    locked: "قفل",
    markDone: "علامت به‌عنوان خوانده‌شده",
    completed: "تکمیل شد",
    paidSoon: "فروش این دوره به‌زودی فعال می‌شود. ایمیلت را بگذار تا خبرت کنم.",
    levelBeginner: "مقدماتی",
    levelIntermediate: "متوسط",
    levelAdvanced: "پیشرفته",
  },
  work: {
    title: "همکاری با من",
    sub: "برای مشاوره AI، اتوماسیون و آموزش سازمانی، فرم زیر را پر کن.",
    services: "خدمات",
    formTitle: "فرم درخواست پروژه",
    name: "نام",
    company: "شرکت",
    email: "ایمیل",
    phone: "تلفن",
    country: "کشور",
    projectType: "نوع پروژه",
    budget: "بودجه تقریبی",
    message: "شرح پروژه",
    unsure: "مطمئن نیستم به چه راه‌حل AI نیاز دارم.",
    send: "ارسال درخواست",
    done: "درخواستت ثبت شد. به‌زودی باهات تماس می‌گیرم.",
  },
  contact: {
    title: "تماس با من",
    sub: "سوال، پیشنهاد یا درخواست همکاری؟ پیام بگذار.",
    name: "نام",
    email: "ایمیل",
    subject: "موضوع",
    message: "متن پیام",
    send: "ارسال پیام",
    done: "پیامت رسید. ممنون!",
  },
  search: {
    title: "جستجو",
    placeholder: "دنبال چه می‌گردی؟ دوره، مقاله، ابزار...",
    button: "جستجو",
    noResults: "نتیجه‌ای پیدا نشد.",
    articles: "مقالات و آموزش‌ها",
    courses: "دوره‌ها",
    tools: "ابزارها",
    projects: "پروژه‌ها",
  },
  common: {
    readMore: "ادامه مطلب",
    back: "بازگشت",
    save: "ذخیره",
    saved: "ذخیره شد",
    loginNeeded: "برای این کار باید وارد شوی.",
    all: "همه",
    beginner: "مقدماتی",
    intermediate: "متوسط",
    advanced: "پیشرفته",
    by: "نویسنده:",
    share: "اشتراک‌گذاری",
    tags: "برچسب‌ها",
    category: "دسته‌بندی",
    publishedAt: "منتشر شده در",
    minRead: "دقیقه مطالعه",
  },
  admin: {
    title: "پنل مدیریت",
    overview: "نمای کلی",
    articles: "مقالات و آموزش‌ها",
    courses: "دوره‌ها",
    users: "کاربران",
    tools: "ابزارها",
    projects: "پروژه‌ها",
    journey: "مسیر من",
    inquiries: "درخواست‌ها",
    messages: "پیام‌ها",
    newsletter: "خبرنامه",
    settings: "تنظیمات",
    activity: "فعالیت‌های اخیر",
    totalUsers: "کل کاربران",
    newUsers: "ثبت‌نام ۷ روز اخیر",
    published: "منتشرشده",
    enrollments: "ثبت‌نام‌ها",
    popular: "محتوای پربازدید",
    viewSite: "مشاهده سایت",
  },
};

export type Dict = typeof fa;

const en: Dict = {
  brandTagline: "Practical AI for Work, Engineering and Life",
  nav: {
    home: "Home",
    learn: "Learn AI",
    courses: "Courses",
    tools: "AI Tools",
    projects: "Projects",
    blog: "Blog",
    journey: "My Journey",
    about: "About",
    work: "Work With Me",
    contact: "Contact",
    dashboard: "Dashboard",
    admin: "Admin",
    login: "Login / Sign up",
    logout: "Logout",
    search: "Search...",
  },
  hero: {
    badge: "Practical AI education",
    titleA: "Learn AI for the",
    titleB: "Real World",
    sub: "I'm Mohammad Poraee — electrical engineer and AI practitioner. No hype, no dry theory: learn to actually use AI in engineering, business and everyday life.",
    ctaStart: "Start Learning",
    ctaExplore: "Explore AI Tutorials",
    ctaWork: "Work With Me",
    philosophy: "Learn. Test. Build. Share.",
  },
  home: {
    statsLearners: "Learners",
    statsTutorials: "Tutorials & articles",
    statsCourses: "Courses",
    statsTools: "Reviewed tools",
    learnTitle: "AI Learning Hub",
    learnSub: "From zero to professional use — pick your path.",
    featuredCourses: "Featured Courses",
    featuredCoursesSub: "Structured, project-based, practical training.",
    latestArticles: "Latest Articles",
    latestArticlesSub: "Practical notes from working with AI.",
    toolsTitle: "Tools I've personally tested",
    toolsSub: "No ads — only tools worth your time.",
    projectsTitle: "Projects & case studies",
    projectsSub: "Real problems, real solutions, real results.",
    journeyTitle: "Building in Public",
    journeySub: "Learning and building openly — join the journey.",
    igTitle: "My Instagram",
    igSub: "Follow for short daily AI lessons.",
    igFollow: "Follow on Instagram",
    newsletterTitle: "Get Practical AI Lessons in Your Inbox",
    newsletterSub: "One short, useful email per week. No spam.",
    newsletterPlaceholder: "Your email",
    newsletterButton: "Subscribe",
    newsletterDone: "You're subscribed. See you soon!",
    viewAll: "View all",
    free: "Free",
    paid: "Paid",
    comingSoon: "Soon",
    min: "min",
    lessons: "lessons",
  },
  footer: {
    about: "Mohammad Poraee — electrical engineer and practical AI educator. I help you actually use AI at work, in engineering and in life.",
    quickLinks: "Quick Links",
    categories: "Popular Categories",
    connect: "Connect",
    rights: "All rights reserved.",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    madeWith: "Crafted with care for AI learners",
  },
  auth: {
    loginTitle: "Login / Sign up",
    loginSub: "Sign in with your mobile number — no password needed.",
    phoneLabel: "Mobile number",
    phonePlaceholder: "09123456789",
    sendCode: "Send verification code",
    codeLabel: "6-digit code",
    verify: "Verify & login",
    resend: "Resend code",
    backToPhone: "Change number",
    demoBox: "Demo mode is ON — your code:",
    demoHint: "In production this code arrives via SMS.",
    errors: {
      invalid_phone: "Invalid mobile number.",
      cooldown: "Please wait a moment and retry.",
      rate_limited: "Too many requests; try later.",
      sms_failed: "Failed to send SMS.",
      wrong_code: "Wrong code.",
      expired: "Code expired; request a new one.",
      locked: "Locked after too many attempts; request a new code.",
      not_found: "No code found for this number.",
    } as Record<string, string>,
  },
  dashboard: {
    title: "My Dashboard",
    welcome: "Welcome back",
    overview: "Overview",
    myCourses: "My Courses",
    saved: "Saved",
    history: "Learning History",
    settings: "Account Settings",
    profile: "Profile",
    enrolled: "Enrolled courses",
    completed: "Completed courses",
    inProgress: "In progress",
    continueCourse: "Continue learning",
    noCourses: "You haven't enrolled in any course yet.",
    browseCourses: "Browse courses",
    noSaved: "Nothing saved yet.",
    noHistory: "No history recorded.",
    name: "Full name",
    phone: "Mobile number",
    email: "Email (optional)",
    language: "Preferred language",
    save: "Save changes",
    saved2: "Changes saved.",
    notifications: "Notifications",
    noNotifications: "No notifications.",
    devices: "Devices",
    logoutAll: "Logout from all devices",
    progress: "Progress",
  },
  courses: {
    enroll: "Enroll in course",
    enrolled: "Enrolled",
    loginToEnroll: "Login to enroll",
    notifyMe: "Notify me",
    outcomes: "What you'll learn",
    audience: "Who this is for",
    prereq: "Prerequisites",
    modules: "Curriculum",
    instructor: "Instructor",
    level: "Level",
    freeLesson: "Free",
    locked: "Locked",
    markDone: "Mark as complete",
    completed: "Completed",
    paidSoon: "Sales open soon. Leave your email and I'll notify you.",
    levelBeginner: "Beginner",
    levelIntermediate: "Intermediate",
    levelAdvanced: "Advanced",
  },
  work: {
    title: "Work With Me",
    sub: "For AI consulting, automation and corporate training, fill the form below.",
    services: "Services",
    formTitle: "Project inquiry form",
    name: "Name",
    company: "Company",
    email: "Email",
    phone: "Phone",
    country: "Country",
    projectType: "Project type",
    budget: "Estimated budget",
    message: "Project description",
    unsure: "I'm not sure what AI solution I need.",
    send: "Send request",
    done: "Request received. I'll get back to you soon.",
  },
  contact: {
    title: "Contact Me",
    sub: "Questions, ideas or collaboration? Drop a message.",
    name: "Name",
    email: "Email",
    subject: "Subject",
    message: "Your message",
    send: "Send message",
    done: "Message received. Thank you!",
  },
  search: {
    title: "Search",
    placeholder: "What are you looking for? Courses, articles, tools...",
    button: "Search",
    noResults: "No results found.",
    articles: "Articles & tutorials",
    courses: "Courses",
    tools: "Tools",
    projects: "Projects",
  },
  common: {
    readMore: "Read more",
    back: "Back",
    save: "Save",
    saved: "Saved",
    loginNeeded: "Please login first.",
    all: "All",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    by: "By",
    share: "Share",
    tags: "Tags",
    category: "Category",
    publishedAt: "Published on",
    minRead: "min read",
  },
  admin: {
    title: "Admin Dashboard",
    overview: "Overview",
    articles: "Articles & Tutorials",
    courses: "Courses",
    users: "Users",
    tools: "Tools",
    projects: "Projects",
    journey: "Journey",
    inquiries: "Inquiries",
    messages: "Messages",
    newsletter: "Newsletter",
    settings: "Settings",
    activity: "Recent Activity",
    totalUsers: "Total users",
    newUsers: "New in 7 days",
    published: "Published",
    enrollments: "Enrollments",
    popular: "Popular content",
    viewSite: "View site",
  },
};

export function getDict(lang: Lang): Dict {
  return lang === "fa" ? fa : en;
}
