// PorAI extra seed — batch 2 tutorials (FA + EN).
// Run: npx tsx scripts/seed-extra.ts (also safe to re-run)

import { Cats, Tags, Articles } from "../db";

const posts = [
  {
    slug: "how-to-use-ai", kind: "tutorial", status: "published",
    category: "ai-basics", difficulty: "beginner", readMinutes: 10,
    titleFa: "نحوه استفاده از هوش مصنوعی: راهنمای قدم‌به‌قدم برای شروع",
    titleEn: "How to Use AI: A Step-by-Step Starter Guide",
    excerptFa: "اگر تازه شروع کرده‌ای، این نقشه راه توست: انتخاب ابزار، اولین گفت‌وگو، و ۵ کاربردی که از همین امروز وقتت را آزاد می‌کند.",
    excerptEn: "New to AI? Your roadmap: picking a tool, the first conversation, and 5 uses that free up your time starting today.",
    contentFa: `## قدم صفر: ذهنیت درست\n\nهوش مصنوعی «جادو» نیست؛ یک دستیار خیلی سریع و گاهی اشتباه‌کار است. فرمول برنده: **تو فکر می‌کنی و تصمیم می‌گیری، AI پیش‌نویس می‌زند و سرعت می‌دهد.**\n\n## قدم ۱: یک ابزار انتخاب کن\n\nبرای شروع فقط یکی کافی است:\n\n- **ChatGPT** — همه‌کاره و مناسب شروع\n- **Claude** — عالی برای متن‌های بلند و دقیق\n- **Gemini** — اگر در اکوسیستم گوگل هستی\n\nیک حساب رایگان بساز و وارد شو. همین.\n\n## قدم ۲: اولین گفت‌وگوی درست\n\nبه‌جای «سلام، چه خبر؟» یک کار واقعی بده:\n\n\`\`\`\nمن یک مهندس برق هستم و باید ایمیل هفتگی پیشرفت پروژه بنویسم.\nاین یادداشت‌های خام من است: [...]\nآن‌ها را به یک ایمیل رسمی و مرتب تبدیل کن.\n\`\`\`\n\n## ۵ کاربرد روز اول\n\n1. **خلاصه‌سازی:** متن بلند بده، خلاصه ۵ خطی بگیر.\n2. **ایمیل و نامه:** پیش‌نویس بگیر، خودت نهایی کن.\n3. **ایده‌پردازی:** برای هر مسئله ۱۰ ایده بخواه.\n4. **یادگیری:** هر مفهومی را «مثل اینکه ۱۰ ساله‌ام» توضیح بخواه.\n5. **ترجمه:** فارسی به انگلیسی رسمی و برعکس.\n\n## ۳ قانون طلایی\n\n- **همیشه راستی‌آزمایی کن** — مخصوصاً اعداد، تاریخ‌ها و مسائل حقوقی/پزشکی/مهندسی.\n- **اطلاعات محرمانه نده** — رمز، داده مشتری و اسناد محرمانه شرکت ممنوع.\n- **گفت‌وگو کن، نه تک‌پرامپت** — جواب اول پیش‌نویس است؛ بگو «کوتاه‌ترش کن»، «رسمی‌تر بنویس»، «مثال بزن».\n\n> قدم بعدی: آموزش [مهندسی پرامپت در ۳۰ دقیقه](/fa/learn/prompt-engineering-30-minutes) را بخوان.`,
    contentEn: `## Step zero: the right mindset\n\nAI is not magic; it's a very fast assistant that sometimes makes mistakes. The winning formula: **you think and decide, AI drafts and accelerates.**\n\n## Step 1: pick ONE tool\n\nFor starters, one is enough:\n\n- **ChatGPT** — the all-rounder, great to begin\n- **Claude** — excellent for long, precise documents\n- **Gemini** — if you live in Google's ecosystem\n\nCreate a free account and sign in. That's it.\n\n## Step 2: your first real conversation\n\nInstead of "hello, what's up?", give it real work:\n\n\`\`\`\nI'm an electrical engineer and must write a weekly progress email.\nHere are my raw notes: [...]\nTurn them into a formal, tidy email.\n\`\`\`\n\n## 5 day-one uses\n\n1. **Summarize:** long text in, 5-line summary out.\n2. **Emails:** get a draft, finalize it yourself.\n3. **Brainstorm:** ask for 10 ideas per problem.\n4. **Learn:** ask to explain any concept "like I'm 10".\n5. **Translate:** to formal English and back.\n\n## 3 golden rules\n\n- **Always verify** — especially numbers, dates, and legal/medical/engineering matters.\n- **Never share secrets** — no passwords, customer data, or confidential company docs.\n- **Converse, don't one-shot** — the first answer is a draft; say "make it shorter", "more formal", "give an example".\n\n> Next step: read [Prompt Engineering in 30 Minutes](/en/learn/prompt-engineering-30-minutes).`,
  },
  {
    slug: "how-to-write-prompts", kind: "tutorial", status: "published",
    category: "prompt-engineering", difficulty: "beginner", readMinutes: 14,
    titleFa: "نحوه پرامپت‌نویسی: از جمله ساده تا دستور حرفه‌ای",
    titleEn: "How to Write Prompts: From Simple Sentences to Pro Instructions",
    excerptFa: "پرامپت‌نویسی مهارتِ «درست خواستن» است: فرمول عملی، ۷ تکنیک، مثال‌های واقعی و چک‌لیست نهایی.",
    excerptEn: "Prompting is the skill of asking well: a practical formula, 7 techniques, real examples and a final checklist.",
    contentFa: `## پرامپت خوب یعنی چه؟\n\nپرامپت خوب ۴ چیز را مشخص می‌کند: **کی جواب بدهد، در چه زمینه‌ای، دقیقاً چه کاری بکند، و خروجی چه شکلی باشد.**\n\n## فرمول عملی: نقش + زمینه + وظیفه + قالب + معیار\n\n\`\`\`\nنقش: تو یک ویراستار حرفه‌ای فارسی هستی.\nزمینه: دارم پست لینکدین درباره اتوماسیون گزارش‌ها می‌نویسم.\nوظیفه: این پیش‌نویس را ویرایش کن.\nقالب: متن نهایی + ۳ پیشنهاد برای جمله اول.\nمعیار: لحن حرفه‌ای ولی صمیمی، حداکثر ۱۵۰ کلمه.\n\`\`\`\n\n## ۷ تکنیکی که تفاوت می‌سازند\n\n1. **مثال بده:** یک نمونه خروجی ایده‌آل بچسبان؛ AI سبکت را می‌گیرد.\n2. **قدم‌به‌قدم بخواه:** «قبل از جواب نهایی، قدم‌های فکر کردنت را بنویس.»\n3. **نقش بده:** «مثل یک حسابرس بدبین، این طرح را نقد کن.»\n4. **محدودیت بگذار:** تعداد کلمه، لحن، مخاطب، چیزهایی که نباید بگوید.\n5. **سوال بپرس، جواب بگیر:** «قبل از نوشتن، ۵ سوال بپرس تا نیازم را دقیق بفهمی.»\n6. **چند نسخه بخواه:** «۳ نسخه بده: کوتاه، کامل و خلاقانه.»\n7. **تکرار کن:** «خوب بود؛ حالا رسمی‌تر و نصف حجم.»\n\n## اشتباهات رایج\n\n- ❌ «یک متن درباره موفقیت بنویس» (کلی و بی‌زمینه)\n- ✅ «برای لینکدین، ۱۲۰ کلمه درباره درسی که از شکست پروژه X گرفتم...»\n\n## چک‌لیست قبل از ارسال\n\n- آیا نقش مشخص است؟ زمینه؟ وظیفه دقیق؟ قالب خروجی؟ معیار کیفیت؟\n- اگر AI از من سوال داشت، چه می‌پرسید؟ همان را خودم اول جواب بدهم.`,
    contentEn: `## What is a good prompt?\n\nA good prompt defines 4 things: **who answers, in what context, exactly what to do, and what shape the output takes.**\n\n## The practical formula: Role + Context + Task + Format + Bar\n\n\`\`\`\nRole: You are a professional editor.\nContext: I'm writing a LinkedIn post about report automation.\nTask: Edit this draft.\nFormat: final text + 3 options for the opening line.\nBar: professional yet warm tone, max 150 words.\n\`\`\`\n\n## 7 techniques that make the difference\n\n1. **Give an example:** paste one ideal output; AI picks up your style.\n2. **Ask for steps:** "Before the final answer, show your reasoning steps."\n3. **Assign a role:** "Like a skeptical auditor, critique this plan."\n4. **Set constraints:** word count, tone, audience, what NOT to say.\n5. **Let it ask:** "Ask me 5 questions first to understand my need."\n6. **Ask for versions:** "Give 3 versions: short, complete, creative."\n7. **Iterate:** "Good; now more formal and half the length."\n\n## Common mistakes\n\n- ❌ "Write about success" (vague, no context)\n- ✅ "For LinkedIn, 120 words on the lesson I learned from project X failing..."\n\n## Pre-send checklist\n\n- Is the role clear? Context? Exact task? Output format? Quality bar?\n- If AI could ask me one question, what would it be? Answer it upfront.`,
  },
  {
    slug: "how-to-use-ai-skills", kind: "tutorial", status: "published",
    category: "ai-tools", difficulty: "intermediate", readMinutes: 11,
    titleFa: "نحوه استفاده از Skills در دستیارهای هوش مصنوعی",
    titleEn: "How to Use Skills in AI Assistants",
    excerptFa: "اسکیل‌ها یعنی «تخصص آماده»: یک‌بار بساز، همیشه استفاده کن. آموزش عملی Skills در Claude و معادل آن در ChatGPT.",
    excerptEn: "Skills are reusable expertise: build once, use forever. A practical guide to Skills in Claude and equivalents in ChatGPT.",
    contentFa: `## اسکیل (Skill) چیست؟\n\nاسکیل یک بسته «دانش + دستورالعمل» است که به AI می‌دهی تا در کارهای تکراری، همیشه به سبک تو عمل کند. مثال: اسکیل «گزارش‌نویسی مهندسی» که هر یادداشت خام را به گزارش استاندارد شرکتت تبدیل می‌کند.\n\n## کجاها اسکیل داریم؟\n\n- **Claude Skills:** اسکیل‌های آماده و قابل ساخت برای تحلیل فایل، گزارش، کدنویسی و...\n- **ChatGPT (GPTs و Custom Instructions):** دستیار اختصاصی خودت را بساز.\n- **Claude Projects / ChatGPT Projects:** دانش ثابت + دستورالعمل برای یک پروژه.\n\n## قدم‌به‌قدم: ساخت اولین اسکیل کاربردی\n\n1. **یک کار تکراری انتخاب کن** — مثلاً «خلاصه جلسه به فرمت شرکت».\n2. **بهترین نمونه خروجی را پیدا کن** — یک نمونه عالی که قبلاً تایید شده.\n3. **قانون‌ها را بنویس:**\n\n\`\`\`\nهر خلاصه جلسه باید شامل باشد:\n1. تصمیم‌ها (حداکثر ۵ مورد)\n2. اقدام‌ها با مسئول و ددلاین\n3. موضوعات باز\nلحن: رسمی، کوتاه، بدون حاشیه.\n\`\`\`\n\n4. **تست کن و اصلاح کن** — روی ۳ نمونه واقعی امتحان کن تا پایدار شود.\n5. **ذخیره‌اش کن** — در Skills یا Project تا همیشه در دسترس باشد.\n\n## ۳ ایده اسکیل برای شروع\n\n- 📝 تبدیل یادداشت به ایمیل رسمی\n- 📊 تبدیل داده خام به جدول تحلیلی\n- 🔍 چک‌لیست بازبینی مدارک (مهندسی)\n\n> قانون من: هر کاری را که ۳ بار تکرار کردی، کاندیدای اسکیل است.`,
    contentEn: `## What is a Skill?\n\nA Skill is a "knowledge + instructions" pack you give AI so it handles recurring work your way, every time. Example: an "engineering reports" skill turning raw notes into your company's standard report.\n\n## Where do Skills live?\n\n- **Claude Skills:** ready-made and custom skills for file analysis, reports, coding...\n- **ChatGPT (GPTs & Custom Instructions):** build your own assistant.\n- **Claude / ChatGPT Projects:** fixed knowledge + instructions per project.\n\n## Step by step: your first useful skill\n\n1. **Pick a recurring task** — e.g. "meeting notes to company format".\n2. **Find the best sample output** — one great, approved example.\n3. **Write the rules:**\n\n\`\`\`\nEvery meeting summary must include:\n1. Decisions (max 5)\n2. Actions with owner + deadline\n3. Open topics\nTone: formal, short, no fluff.\n\`\`\`\n\n4. **Test and refine** — try on 3 real samples until stable.\n5. **Save it** — in Skills or a Project for permanent access.\n\n## 3 starter skill ideas\n\n- 📝 Notes to formal email\n- 📊 Raw data to analysis table\n- 🔍 Document review checklist (engineering)\n\n> My rule: anything you repeat 3 times is a skill candidate.`,
  },
  {
    slug: "ai-tools-landscape", kind: "tutorial", status: "published",
    category: "ai-tools", difficulty: "beginner", readMinutes: 12,
    titleFa: "ابزارهای مختلف هوش مصنوعی: نقشه راه انتخاب ابزار درست",
    titleEn: "AI Tools Landscape: How to Pick the Right Tool",
    excerptFa: "صدها ابزار، یک راهنما: ۷ دسته اصلی ابزارهای AI، بهترین هر دسته از تجربه من، و روش انتخاب بدون سردرگمی.",
    excerptEn: "Hundreds of tools, one guide: 7 main AI tool categories, my pick in each, and a no-confusion selection method.",
    contentFa: `## اول: دسته‌بندی، بعد انتخاب\n\nاشتباه رایج: دنبال «بهترین ابزار AI» گشتن. درستش: اول کارت را مشخص کن، بعد ابزار آن دسته را انتخاب کن.\n\n## ۷ دسته اصلی + انتخاب من\n\n1. **دستیار متنی (چت‌بات):** نوشتن، تحلیل، ایده — انتخاب من: **ChatGPT** و **Claude** (هر دو را داشته باش).\n2. **جست‌وجو و تحقیق:** جواب با منبع — انتخاب من: **Perplexity**.\n3. **یادگیری از روی مدارک خودت:** پرسش از PDF — انتخاب من: **NotebookLM** (رایگان و عالی).\n4. **تولید تصویر:** کاور، پروفایل، ایده بصری — انتخاب من: **Midjourney** (هنری) و **DALL-E/GPT Image** (دقیق).\n5. **صوت و ویدیو:** تبدیل متن به گفتار، تدوین — انتخاب من: **ElevenLabs** (صدا).\n6. **اتوماسیون:** اتصال ابزارها و فرایند خودکار — انتخاب من: **Make**.\n7. **کدنویسی:** کمک‌برنامه‌نویس — انتخاب من: **Claude** و **Cursor**.\n\n## روش انتخاب در ۳ سوال\n\n1. دقیقاً چه خروجی می‌خواهم؟ (متن؟ تصویر؟ خودکارسازی؟)\n2. هفته‌ای چند بار استفاده می‌کنم؟ (کمتر از ۳ بار → رایگان کافی است)\n3. داده‌ام چقدر حساس است؟ (حساس → ابزار معتبر + نسخه سازمانی)\n\n## قانون ضدسردرگمی\n\nبیشتر از **۳ ابزار فعال** نداشته باش: یک چت‌بات اصلی، یک ابزار تحقیق، یک ابزار تخصصی کارت. بقیه را فقط وقتی نیاز شد امتحان کن.\n\n> همه این ابزارها را با بررسی کامل در [بخش ابزارها](/fa/tools) گذاشته‌ام.`,
    contentEn: `## First categorize, then choose\n\nCommon mistake: searching for "the best AI tool". The right way: define your job first, then pick that category's tool.\n\n## 7 main categories + my pick\n\n1. **Text assistants (chatbots):** writing, analysis, ideas — my pick: **ChatGPT** and **Claude** (keep both).\n2. **Search & research:** answers with sources — my pick: **Perplexity**.\n3. **Learn from YOUR docs:** Q&A over PDFs — my pick: **NotebookLM** (free and great).\n4. **Image generation:** covers, avatars, visual ideas — my pick: **Midjourney** (artistic), **DALL-E/GPT Image** (precise).\n5. **Audio & video:** text-to-speech, editing — my pick: **ElevenLabs** (voice).\n6. **Automation:** connecting apps and workflows — my pick: **Make**.\n7. **Coding:** pair programmer — my pick: **Claude** and **Cursor**.\n\n## The 3-question selection method\n\n1. What exact output do I want? (text? image? automation?)\n2. How often weekly? (under 3x → free tier is enough)\n3. How sensitive is my data? (sensitive → reputable tool + business plan)\n\n## The anti-overwhelm rule\n\nKeep at most **3 active tools**: one main chatbot, one research tool, one specialty tool. Try others only when needed.\n\n> All these tools with full reviews live in the [Tools section](/en/tools).`,
  },
  {
    slug: "profile-picture-prompts", kind: "tutorial", status: "published",
    category: "ai-content", difficulty: "beginner", readMinutes: 9,
    titleFa: "۵ پرامپت آماده برای ساخت عکس پروفایل حرفه‌ای با AI",
    titleEn: "5 Ready Prompts for a Professional AI Profile Picture",
    excerptFa: "کپی کن، شخصی‌سازی کن، بساز: ۵ پرامپت تست‌شده برای عکس پروفایل کاری، با نکته‌های مهم شباهت و اخلاق.",
    excerptEn: "Copy, personalize, generate: 5 tested prompts for a professional profile photo, plus key notes on likeness and ethics.",
    contentFa: `## قبل از شروع: ۳ نکته مهم\n\n1. **شباهت:** برای اینکه شبیه خودت شود، از ابزارهایی استفاده کن که عکس مرجع می‌گیرند (مثل FaceID در Midjourney یا آپلود عکس در GPT Image) و ۱۰ تا بساز تا ۲ تای خوب را انتخاب کنی.\n2. **صداقت:** عکس AI برای پروفایل لینکدین/اینستاگرام اشکالی ندارد، ولی برای مدارک رسمی استفاده نکن.\n3. **نور و پس‌زمینه ساده** ۸۰٪ حرفه‌ای بودن عکس است.\n\n## ۵ پرامپت آماده (انگلیسی جواب بهتری می‌دهد)\n\n### ۱. کلاسیک شرکتی\n\n\`\`\`\nProfessional corporate headshot of a [man in his 30s, short dark hair, light beard],\nwearing a navy suit and white shirt, neutral gray studio background,\nsoft studio lighting, sharp focus, confident subtle smile,\nLinkedIn profile photo style, photorealistic, 4k\n\`\`\`\n\n### ۲. مهندس در محیط کار\n\n\`\`\`\nProfessional portrait of an electrical engineer in a modern industrial office,\nwhite shirt, blurred high-tech background, natural window light,\nconfident and approachable, photorealistic, shallow depth of field\n\`\`\`\n\n### ۳. مینیمال مدرن\n\n\`\`\`\nMinimalist professional profile photo, plain light background,\nsmart casual dark shirt, soft daylight, clean composition,\ncentered head and shoulders, ultra realistic\n\`\`\`\n\n### ۴. فضای باز (طبیعی و صمیمی)\n\n\`\`\`\nOutdoor professional headshot, blurred city park background,\ngolden hour lighting, smart blazer, genuine soft smile,\nphotorealistic, high detail\n\`\`\`\n\n### ۵. استودیویی تیره (جدی و قدرتمند)\n\n\`\`\`\nDramatic studio portrait, dark background, rim lighting,\nblack shirt, serious confident expression,\nprofessional executive style, ultra detailed, photorealistic\n\`\`\`\n\n## چطور شخصی‌سازی کنی؟\n\n- مشخصات ظاهری خودت را جای [...] بگذار: سن، مدل مو، ریش، عینک.\n- شغلت را بگو تا لباس و فضا درست شود.\n- آخرش همیشه: **photorealistic, high detail** را نگه دار.\n\n> پیشنهاد من: ۵ تایی بساز، بهترین را انتخاب کن و کمی با [ابزارهای ویرایش عکس](/fa/tools) روتوش کن.`,
    contentEn: `## Before you start: 3 important notes\n\n1. **Likeness:** to look like you, use tools that accept a reference photo (e.g. FaceID in Midjourney or image upload in GPT Image), generate 10, and pick the best 2.\n2. **Honesty:** AI photos are fine for LinkedIn/Instagram, but never for official documents.\n3. **Light + simple background** is 80% of looking professional.\n\n## 5 ready prompts\n\n### 1. Classic corporate\n\n\`\`\`\nProfessional corporate headshot of a [man in his 30s, short dark hair, light beard],\nwearing a navy suit and white shirt, neutral gray studio background,\nsoft studio lighting, sharp focus, confident subtle smile,\nLinkedIn profile photo style, photorealistic, 4k\n\`\`\`\n\n### 2. Engineer at work\n\n\`\`\`\nProfessional portrait of an electrical engineer in a modern industrial office,\nwhite shirt, blurred high-tech background, natural window light,\nconfident and approachable, photorealistic, shallow depth of field\n\`\`\`\n\n### 3. Minimal modern\n\n\`\`\`\nMinimalist professional profile photo, plain light background,\nsmart casual dark shirt, soft daylight, clean composition,\ncentered head and shoulders, ultra realistic\n\`\`\`\n\n### 4. Outdoors (natural and warm)\n\n\`\`\`\nOutdoor professional headshot, blurred city park background,\ngolden hour lighting, smart blazer, genuine soft smile,\nphotorealistic, high detail\n\`\`\`\n\n### 5. Dark studio (serious and strong)\n\n\`\`\`\nDramatic studio portrait, dark background, rim lighting,\nblack shirt, serious confident expression,\nprofessional executive style, ultra detailed, photorealistic\n\`\`\`\n\n## How to personalize\n\n- Put your own features in [...]: age, hairstyle, beard, glasses.\n- State your job so clothing and setting match.\n- Always keep at the end: **photorealistic, high detail**.\n\n> My suggestion: generate 5, pick the best, and lightly retouch with [photo editing tools](/en/tools).`,
  },
  {
    slug: "ai-financial-market-analysis", kind: "tutorial", status: "published",
    category: "ai-economics", difficulty: "intermediate", readMinutes: 13,
    titleFa: "نحوه تحلیل بازارهای مالی با هوش مصنوعی (روش حرفه‌ای)",
    titleEn: "How to Analyze Financial Markets with AI (The Professional Way)",
    excerptFa: "AI پیشگو نیست، تحلیلگر است: روش درست استفاده از AI برای بررسی اخبار، داده‌ها و سناریوهای بازار — با مدیریت ریسک.",
    excerptEn: "AI is not an oracle, it's an analyst: the right way to use AI for news, data and market scenarios — with risk management.",
    contentFa: `## ⚠️ سلب مسئولیت اول\n\nاین آموزش «سیگنال خرید/فروش» نیست. AI نمی‌تواند آینده بازار را پیش‌بینی کند و هرکس خلافش را گفت، یا نمی‌فهمد یا می‌خواهد چیزی بفروشد. کاربرد درست AI: **تحلیل سریع‌تر و تصمیم منظم‌تر.**\n\n## AI در تحلیل مالی به چه دردی می‌خورد؟\n\n1. **خلاصه اخبار:** ۲۰ خبر را بده، ۵ نکته اثرگذار بگیر.\n2. **خواندن گزارش‌ها:** گزارش‌های بلند (صورت مالی، تحلیل‌ها) را خلاصه و نکته‌یابی کن.\n3. **سناریوسازی:** «اگر نرخ بهره X شود، چه سناریوهایی برای شاخص Y محتمل است؟»\n4. **چک‌لیست تصمیم:** قبل از هر معامله، AI را وادار کن مخالف‌خوانی کند.\n5. **آموزش مفاهیم:** هر اندیکاتور را با مثال ساده یاد بگیر.\n\n## ورک‌فلو پیشنهادی من (هفته‌ای ۳۰ دقیقه)\n\n1. اخبار مهم هفته را جمع کن (خبرگزاری‌های معتبر).\n2. به AI بده و بخواه: «در ۱۰ خط: چه شد، چرا مهم است، روی چه بازارهایی اثر دارد.»\n3. از AI بخواه ۳ سناریو (صعودی/نزولی/خنثی) با «نشانه‌های ابطال» هرکدام بنویسد.\n4. خودت تصمیم بگیر و حد ضرر را **قبل** از ورود مشخص کن.\n\n## پرامپت مخالف‌خوان (مهم‌ترین پرامپت این آموزش)\n\n\`\`\`\nمن می‌خواهم [دارایی X] را به این دلایل بخرم: [...]\nتو نقش یک تحلیلگر بدبین را بازی کن و ۵ دلیل مخالف\nو ۳ ریسکی که نادیده گرفته‌ام بنویس. رک و مستقیم باش.\n\`\`\`\n\n## ۴ خط قرمز\n\n- ❌ تصمیم‌گیری کامل را به AI نسپار.\n- ❌ با پول قرضی یا ضروری وارد نشو — AI ریسک را حذف نمی‌کند.\n- ❌ به «ربات تضمینی سود» اعتماد نکن.\n- ✅ همیشه حد ضرر داشته باش و به آن پایبند بمان.`,
    contentEn: `## ⚠️ Disclaimer first\n\nThis is NOT buy/sell advice. AI cannot predict markets, and anyone claiming otherwise either doesn't understand or wants to sell something. AI's proper use: **faster analysis and more disciplined decisions.**\n\n## What is AI good for in market analysis?\n\n1. **News digest:** 20 articles in, 5 market-moving points out.\n2. **Reading reports:** summarize long filings and research, extract key points.\n3. **Scenarios:** "If rate X happens, what scenarios for index Y?"\n4. **Decision checklist:** force AI to argue against you before every trade.\n5. **Learning concepts:** any indicator explained with simple examples.\n\n## My suggested workflow (30 min/week)\n\n1. Collect the week's key news (reputable outlets).\n2. Feed AI and ask: "In 10 lines: what happened, why it matters, which markets it affects."\n3. Ask for 3 scenarios (bull/base/bear) each with "invalidation signals".\n4. Decide yourself and set your stop-loss **before** entry.\n\n## The devil's-advocate prompt (this guide's most important prompt)\n\n\`\`\`\nI want to buy [asset X] for these reasons: [...]\nPlay a bearish analyst: write 5 counter-arguments\nand 3 risks I'm ignoring. Be blunt.\n\`\`\`\n\n## 4 red lines\n\n- ❌ Never outsource the full decision to AI.\n- ❌ Never trade borrowed or essential money — AI doesn't remove risk.\n- ❌ Never trust "guaranteed profit bots".\n- ✅ Always have a stop-loss — and honor it.`,
  },
];

export async function runExtraSeed() {
  const catId = (slug: string) => Cats.bySlug(slug)!.id;
  for (const p of posts) {
    const { category: xc, ...xrest } = p;
    Articles.upsertBySlug(p.slug, {
      ...xrest,
      categoryId: catId(xc),
      authorName: "Mohammad Pouraei",
      views: 60 + p.slug.length * 17,
    } as never);
  }
  const tagId = (slug: string) => (Tags.all().find((t) => (t as { slug: string }).slug === slug) as { id: string } | undefined)?.id;
  const artId = (slug: string) => Articles.bySlug(slug)!.id;
  const link = (slug: string, tags: string[]) => {
    const ids = tags.map(tagId).filter(Boolean) as string[];
    if (ids.length) Tags.setForArticle(artId(slug), ids);
  };
  link("how-to-write-prompts", ["prompt"]);
  link("how-to-use-ai", ["chatgpt"]);
  link("how-to-use-ai-skills", ["chatgpt", "agents"]);
  console.log("Extra seed done:", posts.length, "tutorials.");
}

