// Original beginner lessons, shared by tutorials and the free text course.
export const guides = [
  {
    "slug": "ai-first-steps",
    "category": "ai-basics",
    "readMinutes": 6,
    "titleFa": "هوش مصنوعی چیست؟ اولین تمرین تو در ۱۰ دقیقه",
    "titleEn": "What is AI? Your first ten-minute exercise",
    "excerptFa": "با یک کار کوچک شروع کن: تبدیل یادداشت پراکنده به یک پیام روشن.",
    "excerptEn": "Start small: turn scattered notes into a clear message.",
    "contentFa": "## قرار است چه چیزی یاد بگیری؟\nهوش مصنوعی نام یک خانواده از روش‌های محاسباتی است. ابزارهای مولد می‌توانند بر اساس درخواست تو متن، تصویر یا خروجی‌های دیگر بسازند. ابتدا با یک دستیار متنی کار می‌کنیم. خروجی روان و مطمئن آن الزاماً درست نیست؛ بررسی نتیجه بخشی از کار توست.\n\n## یک مسئله کوچک انتخاب کن\nدر یک دستیار متنی که به آن دسترسی داری، این یادداشت ساختگی را وارد کن: «قرار جمعه ساعت ۵، کتابخانه، دفتر و خودکار، اگر نمی‌رسی خبر بده». برای شروع از اطلاعات غیرخصوصی استفاده کن.\n\n## درخواست آماده\n> این یادداشت را به یک پیام دوستانه فارسی برای گروه مطالعه تبدیل کن. زمان و مکان را دقیق نگه دار. چیزی به اطلاعات اضافه نکن. پیام حداکثر ۶۰ کلمه باشد. در پایان از اعضا بخواه حضورشان را اعلام کنند.\n\n## نتیجه را بررسی کن\n1. آیا جمعه و ساعت ۵ بدون تغییر مانده‌اند؟\n2. آیا مکان تازه یا شماره تلفنی ساخته شده است؟\n3. آیا لحن برای مخاطب مناسب است؟\n4. آیا پیام را پیش از ارسال خودت خوانده‌ای؟\n\n## اگر نتیجه مناسب نبود\nدر همان گفت‌وگو بنویس: «کوتاه‌تر و خودمانی‌تر بنویس؛ اطلاعات اصلی تغییر نکند». اصلاح دقیق معمولاً از تکرار «بهترش کن» مفیدتر است.\n\n## تمرین\nهمان یادداشت را یک بار برای دوست و یک بار برای همکار بازنویسی کن. تفاوت لحن دو خروجی را پیدا کن. موفقیت این تمرین یعنی یک پیام قابل استفاده با اطلاعات درست؛ نه متنی که فقط زیبا به نظر برسد.",
    "contentEn": "## What will you learn?\nAI describes a family of computational methods. Generative tools create text, images or other outputs from instructions. We will start with a text assistant. A fluent, confident answer can still be wrong, so reviewing the result is part of the task.\n\n## Choose one small task\nUse a text assistant you already have access to. Try these fictional notes: “Friday, 5 pm, library, bring a notebook and pen, let us know if you cannot come.” Keep private information out of this exercise.\n\n## Try this prompt\n> Turn these notes into a friendly message for a study group. Keep the time and place exactly as given. Do not add facts. Use no more than 60 words. Finish by asking people to confirm attendance.\n\n## Review the result\n1. Did Friday and 5 pm stay the same?\n2. Did the assistant invent a location or phone number?\n3. Does the tone suit the group?\n4. Have you read the message before sending it?\n\n## Improve one thing at a time\nTry: “Make it shorter and more conversational. Keep every essential detail.” Specific feedback is more useful than simply asking for a better answer.\n\n## Exercise\nRewrite the same notes for a friend and then a colleague. Compare the tone. A successful result is a usable message with accurate details, not merely polished writing."
  },
  {
    "slug": "clear-prompts",
    "category": "prompt-engineering",
    "readMinutes": 7,
    "titleFa": "پرامپت بهتر با چهار بخش ساده",
    "titleEn": "Write clearer prompts in four parts",
    "excerptFa": "هدف، زمینه، محدودیت و شکل خروجی را مشخص کن.",
    "excerptEn": "Specify the task, context, constraints and output format.",
    "contentFa": "## پرامپت یعنی چه؟\nپرامپت همان درخواست یا راهنمایی تو برای ابزار است. لازم نیست پر از اصطلاح باشد. درخواست خوب به ابزار می‌گوید چه کاری انجام دهد و تو چطور نتیجه را ارزیابی می‌کنی.\n\n## چهار بخش کاربردی\n1. **هدف:** چه کاری می‌خواهی؟ مثلاً نوشتن پیش‌نویس یک پیام.\n2. **زمینه:** مخاطب کیست و چه اطلاعاتی باید بداند؟\n3. **محدودیت:** طول، لحن و چیزهایی که نباید تغییر کنند.\n4. **خروجی:** فهرست، جدول یا چند پاراگراف؟\n\n## یک مثال کامل\n> برای همکارم پیش‌نویس پیامی بنویس. می‌خواهم جلسه فردا را از ساعت ۹ به ۱۱ منتقل کنیم. لحن محترمانه و کوتاه باشد. دلیل تغییر را نمی‌دانیم؛ دلیل نساز. خروجی یک پیام حداکثر ۵۰ کلمه‌ای باشد و در پایان تأیید زمان را بخواه.\n\nابزار نباید فرض کند زمان جدید قطعی شده است. عبارت «پیشنهاد می‌کنم» با «جلسه منتقل شد» معنای متفاوتی دارد.\n\n## وقتی اطلاعات کافی نیست\nاضافه کن: «اگر اطلاعات ضروری کم است، قبل از نوشتن از من بپرس». خودت هم پاسخ را بخوان؛ این جمله تضمین نمی‌کند که همه فرض‌ها حذف شوند.\n\n## تمرین\nدرخواست مبهم «برای من برنامه بنویس» را به درخواستی برای ۲۰ دقیقه تمرین زبان تبدیل کن. سطح، هدف روز، زمان و نوع تمرین را مشخص کن. نتیجه را با درخواست اول مقایسه کن.\n\n## چک‌لیست پایان\n- می‌توانم در یک جمله بگویم خروجی چه مشکلی را حل می‌کند.\n- اطلاعات لازم را داده‌ام و اطلاعات خصوصی غیرضروری را حذف کرده‌ام.\n- حداقل یک معیار برای بررسی پاسخ دارم.",
    "contentEn": "## What is a prompt?\nA prompt is your instruction to the tool. Clear requests do not need elaborate terminology. They explain the task and give you a way to judge the result.\n\n## Four useful parts\n1. **Task:** what should the assistant do?\n2. **Context:** who is the audience and what do they need to know?\n3. **Constraints:** length, tone and facts that must stay unchanged.\n4. **Format:** a list, table or a few paragraphs?\n\n## A complete example\n> Draft a message to my colleague proposing that tomorrow’s meeting move from 9 to 11 am. Be polite and brief. We have not provided a reason; do not invent one. Return a message under 50 words, asking them to confirm the time.\n\nThe new time is a proposal. “Could we move it?” and “The meeting has moved” do not mean the same thing.\n\n## Handle missing information\nAdd: “Ask me for essential missing details before writing.” This communicates your expectation but does not guarantee that assumptions disappear. Review the result.\n\n## Exercise\nTurn “Make me a plan” into a prompt for twenty minutes of language practice. Include your level, today’s goal, the available time and the exercise format. Compare the two responses.\n\n## Final check\n- I can explain the intended result in one sentence.\n- I supplied context without unnecessary private information.\n- I have a criterion for checking the answer."
  },
  {
    "slug": "summarize-with-evidence",
    "category": "ai-productivity",
    "readMinutes": 6,
    "titleFa": "خلاصه‌سازی متن بدون گم‌شدن نکته‌های مهم",
    "titleEn": "Summarize a text without losing key details",
    "excerptFa": "خلاصه، اقدام بعدی و اطلاعات نامشخص را از هم جدا کن.",
    "excerptEn": "Separate the summary, next actions and missing information.",
    "contentFa": "## هدف خلاصه را مشخص کن\nمرور سریع، پیدا کردن تصمیم‌ها و فهرست اقدام‌ها خروجی‌های متفاوتی هستند. خلاصه‌ای که برای مطالعه مناسب است، الزاماً برای پیگیری کارها کافی نیست.\n\n## متن تمرین\n«گروه مطالعه جمعه ساعت ۵ در کتابخانه جلسه دارد. سارا تا چهارشنبه فهرست کتاب‌ها را آماده می‌کند. علی پیشنهاد داده جلسه آنلاین هم باشد، اما هنوز تصمیمی نگرفته‌ایم. بودجه خرید کتاب مشخص نشده است.»\n\n## درخواست آماده\n> فقط بر اساس متن بالا پاسخ بده. بخش اول: خلاصه در دو جمله. بخش دوم: اقدام‌ها همراه مسئول و مهلت، فقط اگر در متن آمده است. بخش سوم: موضوع‌های تصمیم‌گیری‌نشده. پیشنهادها را تصمیم قطعی معرفی نکن. اطلاعات ناموجود را «مشخص نشده» بنویس.\n\n## با اصل متن تطبیق بده\nفهرست کتاب‌ها مسئول و مهلت دارد. آنلاین‌بودن جلسه فقط پیشنهاد است. برای بودجه عددی نداریم. اگر خروجی خلاف این موارد بود، جمله اشتباه را مشخص کن و اصلاح بخواه.\n\n## برای متن‌های بلندتر\nبخواه هر نکته به عنوان بخش یا عبارت مربوط در متن اشاره کند. خودت اشاره‌ها را بررسی کن. اگر متن را تکه‌تکه می‌فرستی، بگو تا دریافت همه بخش‌ها جمع‌بندی نکند.\n\n## تمرین\nیک پاراگراف عمومی انتخاب کن. ابتدا خلاصه ۵۰ کلمه‌ای و سپس سه نکته اصلی بخواه. بررسی کن چه چیزی حذف شده است. متن محرمانه محل کار را بدون مجوز وارد سرویس بیرونی نکن.",
    "contentEn": "## Define the purpose\nDo you need an overview, a decision record or an action list? A reading summary may omit details needed to follow up on work.\n\n## Practice text\n“The study group will meet at the library on Friday at 5 pm. Sara will prepare the book list by Wednesday. Ali proposed an online option, but no decision has been made. The book budget is not yet known.”\n\n## Try this prompt\n> Use only this text. First, summarize it in two sentences. Second, list actions with an owner and deadline only where stated. Third, list unresolved questions. Do not turn proposals into decisions. Mark missing information as “not specified.”\n\n## Compare with the original\nThe book list has an owner and deadline. The online option is only a proposal. There is no budget amount. Identify any exact error before requesting a correction.\n\n## For longer texts\nAsk for a section heading or supporting phrase for each point, then check those references. If sending multiple parts, ask the assistant to wait for all parts before summarizing.\n\n## Exercise\nChoose a public paragraph. Request a fifty-word summary and then three key points. Check what was omitted. Do not upload confidential work documents to an external service without authorization."
  },
  {
    "slug": "everyday-ai-plan",
    "category": "ai-growth",
    "readMinutes": 5,
    "titleFa": "یک برنامه روزانه واقع‌بینانه با کمک AI",
    "titleEn": "Make a realistic daily plan with AI",
    "excerptFa": "زمان و اولویت را خودت تعیین کن؛ برای مرتب‌کردن کارها کمک بگیر.",
    "excerptEn": "Set your priorities and use AI to organize the work.",
    "contentFa": "## از زمان واقعی شروع کن\nبرنامه باید در روز تو جا شود. زمان آزاد، کارهای ضروری و محدودیت‌ها را بنویس. دستیار از تقویم تو خبر ندارد مگر اطلاعات لازم را در اختیارش بگذاری.\n\n## مثال\nامروز ۶۰ دقیقه وقت آزاد داری: تمرین زبان، نوشتن یک پیام و مرتب‌کردن فایل‌ها. لازم نیست همه کارها کامل شوند.\n\n## درخواست آماده\n> امروز ۶۰ دقیقه وقت دارم. اولویت من ۲۰ دقیقه زبان است. نوشتن پیام حدود ۱۰ دقیقه طول می‌کشد. باقی زمان را بین مرتب‌کردن فایل‌ها و استراحت کوتاه تقسیم کن. جدول کار، مدت و نشانه پایان بده. جمع زمان از ۶۰ دقیقه بیشتر نشود. هیچ کاری را در تقویم ثبت نکن؛ فقط پیشنهاد بده.\n\n## برنامه را کنترل کن\nجمع دقیقه‌ها را خودت حساب کن. «مرتب‌کردن ۱۰ فایل» پایان روشن‌تری از «مرتب‌کردن همه‌چیز» دارد. اگر زمان کم آوردی، دامنه کار را کوچک کن.\n\n## پایان روز\nزمان واقعی هر کار را یادداشت کن. فردا بگو کدام تخمین درست نبود. معیار پیشرفت، کامل‌بودن فهرست نیست؛ انجام کار مهم و یادگرفتن از زمان واقعی است.\n\n## تمرین\nبرای فردا سه کار مشخص کن. یکی را ضروری علامت بزن و برای دو کار دیگر نسخه کوتاه‌تر تعریف کن. برنامه را با تعهدات واقعی‌ات تطبیق بده.",
    "contentEn": "## Start with real available time\nWrite down available time, essential tasks and constraints. An assistant does not know your calendar unless you provide that information.\n\n## Example\nYou have sixty minutes for language practice, drafting a message and organizing files. You do not need to finish everything.\n\n## Try this prompt\n> I have sixty minutes. My priority is twenty minutes of language practice. Drafting a message should take ten minutes. Divide the rest between organizing files and a short break. Return a table with task, duration and completion criterion. Keep the total within sixty minutes. Suggest a plan only; do not create calendar events.\n\n## Check the plan\nAdd the minutes yourself. “Organize ten files” has a clearer finish than “Organize everything.” Reduce the scope if necessary.\n\n## At the end of the day\nRecord actual time taken. Tomorrow, explain which estimates were wrong. Progress means useful work and learning from actual time, not a perfect-looking schedule.\n\n## Exercise\nChoose three tasks for tomorrow. Mark one essential task and define shorter versions of the others. Compare the plan with your real commitments."
  },
  {
    "slug": "check-ai-answers",
    "category": "ai-basics",
    "readMinutes": 7,
    "titleFa": "چطور جواب هوش مصنوعی را بررسی کنیم؟",
    "titleEn": "How to check an AI answer",
    "excerptFa": "بین واقعیت، فرض و پیشنهاد فرق بگذار و ادعاهای مهم را بررسی کن.",
    "excerptEn": "Separate facts, assumptions and suggestions before trusting an answer.",
    "contentFa": "## لحن مطمئن نشانه صحت نیست\nجواب روان ممکن است شامل نام اشتباه، تاریخ نادرست یا منبع ساختگی باشد. پرسیدن «مطمئنی؟» جای بررسی مستقل را نمی‌گیرد.\n\n## سه نوع جمله\n- **واقعیت قابل بررسی:** مثل تاریخ یک رویداد.\n- **فرض:** مثل اینکه مخاطب همه اصطلاح‌ها را می‌داند.\n- **پیشنهاد:** مثل ترتیب مطالعه سه فصل.\nواقعیت را با منبع بررسی کن، فرض را با شرایط خودت تطبیق بده و پیشنهاد را با هدفت بسنج.\n\n## درخواست کمکی\n> پاسخ قبلی را مرور کن. ادعاهای قابل بررسی، فرض‌ها و پیشنهادها را جدا بنویس. اگر منبعی نداری، صریح بگو. منبع یا لینک نساز. مواردی را که باید مستقل بررسی کنم مشخص کن.\n\n## بررسی عملی\n1. ادعای مهم را دقیق مشخص کن.\n2. صفحه اصلی سازمان یا سند مرجع را پیدا کن.\n3. ببین منبع همان ادعا را پشتیبانی می‌کند یا فقط موضوع مشابه دارد.\n4. تاریخ و نسخه را بررسی کن.\n5. اگر اختلاف باقی ماند، نتیجه را قطعی معرفی نکن.\n\n## تمرین\nبه دستیار بده: «کارگاه دو جلسه دارد؛ هر جلسه ۴۵ دقیقه». بخواه زمان کل را حساب و معرفی کوتاهی بنویسد. عدد باید ۹۰ دقیقه باشد. قیمت، مدرس یا تاریخی که اضافه شود اطلاعات ساخته‌شده است.\n\n## معیار پایان\nبرای هر ادعای مهم بتوانی نشان بدهی از کجا آمده است. در تصمیم‌های تخصصی یا حساس، بررسی فرد متخصص هم لازم است.",
    "contentEn": "## Confidence is not evidence\nA fluent answer can contain an incorrect name, date or invented reference. Asking “Are you sure?” is not independent verification.\n\n## Three kinds of statement\n- **Checkable fact:** an event date.\n- **Assumption:** that a reader knows every technical term.\n- **Suggestion:** a proposed reading order.\nCheck facts against sources, assumptions against your circumstances and suggestions against your goal.\n\n## A useful follow-up\n> Separate the checkable claims, assumptions and suggestions in your answer. Say when you lack a source. Do not invent references or links. Identify what I should independently verify.\n\n## Verification steps\n1. Identify the exact claim that matters.\n2. Find the original organization’s page or reference document.\n3. Check whether it supports that claim, not merely the topic.\n4. Check the date and version.\n5. Keep unresolved uncertainty visible.\n\n## Exercise\nProvide: “The workshop has two forty-five-minute sessions.” Ask for the total duration and a short introduction. The total is ninety minutes. An added price, instructor or date is unsupported.\n\n## Completion criterion\nYou can explain where each important claim came from. Include a qualified person in the review of sensitive or specialist decisions."
  },
  {
    "slug": "first-automation-map",
    "category": "ai-automation",
    "readMinutes": 8,
    "titleFa": "اولین اتوماسیونت را روی کاغذ طراحی کن",
    "titleEn": "Map your first automation before choosing a tool",
    "excerptFa": "ورودی، مراحل، بررسی و خروجی یک کار تکراری را تعریف کن؛ بدون هزینه ابزار.",
    "excerptEn": "Define the input, steps, review and output without buying software.",
    "contentFa": "## اتوماسیون یعنی چه؟\nاتوماسیون یعنی اجرای فرایند با دخالت دستی کمتر. همه اتوماسیون‌ها به AI نیاز ندارند. انتقال فایل با نام مشخص می‌تواند با قواعد ساده انجام شود؛ خلاصه‌کردن متن آزاد ممکن است از AI کمک بگیرد.\n\n## مثال: یادداشت‌های مطالعه\nیادداشت خام باید به خلاصه و فهرست سؤال تبدیل شود. فعلاً فرایند را طراحی و دستی امتحان می‌کنیم؛ هنوز ابزارها به هم وصل نشده‌اند.\n\n## نقشه پنج‌بخشی\n1. **شروع:** یک یادداشت جدید انتخاب می‌شود.\n2. **ورودی:** متن و عنوان یادداشت.\n3. **پردازش:** خلاصه سه‌نکته‌ای و دو سؤال برای مرور.\n4. **بررسی:** خودت خلاصه را با متن اصلی تطبیق می‌دهی.\n5. **خروجی:** نسخه تأییدشده در پوشه مطالعه ذخیره می‌شود.\n\n## درخواست برای طراحی\n> این فرایند را به چک‌لیست قابل اجرای دستی تبدیل کن. برای ورودی خالی، یادداشت تکراری و خلاصه اشتباه، رفتار مشخص پیشنهاد بده. فعلاً ابزار پولی یا ارسال خودکار لازم نیست.\n\n## قبل از اتصال ابزارها\nسه یادداشت متفاوت را پردازش کن. زمان، خطا و تغییر لازم را یادداشت کن. اگر فرایند دستی مبهم باشد، وصل‌کردن ابزارها مشکل را حل نمی‌کند.\n\n## آمادگی برای اجرای خودکار\nورودی و خروجی باید روشن و خطا قابل تشخیص باشد. مشخص کن چه کسی نتیجه را تأیید می‌کند. برای جلوگیری از اجرای تکراری، هر ورودی شناسه یا علامت پردازش داشته باشد. در صورت خطا، فرایند باید متوقف و قابل پیگیری باشد.\n\n## تمرین نهایی\nیک کار تکراری خودت را با این پنج بخش بنویس. نسخه دستی را اجرا کن و بعد درباره ابزار تصمیم بگیر. این خروجی نقشه اتوماسیون است؛ اجرای خودکار هنوز ساخته نشده است.",
    "contentEn": "## What is automation?\nAutomation reduces manual work in a process. It does not always need AI. Moving a file with a known name may use simple rules; summarizing free-form notes may benefit from AI.\n\n## Example: study notes\nTurn a raw note into a summary and review questions. For now, design and try the process manually. No tools have been connected yet.\n\n## A five-part map\n1. **Trigger:** select a new note.\n2. **Input:** the note’s text and title.\n3. **Processing:** a three-point summary and two review questions.\n4. **Review:** compare the summary with the source yourself.\n5. **Output:** save the approved result in your study folder.\n\n## Planning prompt\n> Turn this process into a manual checklist. Suggest explicit behavior for an empty input, duplicate note and inaccurate summary. No paid tools or automatic sending are needed.\n\n## Test before connecting\nProcess three different notes. Record time, errors and changes. Connecting tools does not fix an unclear process.\n\n## Ready to automate?\nInputs and outputs are clear, errors are identifiable and someone owns the review. Use an identifier or processed marker to prevent duplicates. Failed steps should stop and leave an inspectable record.\n\n## Final exercise\nMap a recurring task using these five parts. Try the manual version before choosing software. You have designed an automation plan; you have not yet built an automatic workflow."
  }
];
